version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: thisismysecretary
        databases:
          default:
            connector: postgres
            host: ec2-3-214-4-151.compute-1.amazonaws.com
            database: d7d278pmaba3t5
            user: zlspjhmxftullj
            password: bab1ddf4e069b0577cfe7e939999dabb7ab3ad365b7f8681f658c383c058a376
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true